### ISSUE TITLE
Incorrect Text Capitalization in Cookie Purpose Descriptions Across Languages

### ISSUE THREAD

**Issue by lulienne** [termsfeed/termsfeed-cookie-consent-4-2#1]
**Description:** The cookie purpose descriptions are rendered entirely in lowercase, which affects the accuracy and professionalism of the text, especially for languages like German. This issue likely occurs for all languages due to a `.toLowerCase()` function being applied.

**Expected Behavior:** Cookie purpose descriptions should respect language-specific capitalization rules.

### Attachments: (Screenshot)

Thank you!
<img width="1356" alt="image (1)" src="https://github.com/user-attachments/assets/a9aa5d36-642b-4091-a073-ed58fb47db8c">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2c0c1e8a-6c2c-484b-a994-b02dcf95aa61">

**Comment by termsfeed** [comment]
@lulienne Thank you for the feedback here! We've pushed a fix for this for 4.2.0
